#!/usr/bin/env python3
"""Regenerate the recovery allowlist from checksum-pinned published packages.

Development tool only; installers use the resulting shell data without Python.
Pass the v0.1.0, v0.2.0 and v0.2.1 universal package paths, in any order.
"""
import hashlib
import pathlib
import subprocess
import sys
import tempfile

PACKAGES = {
    "0.1.0": "a4ae851d8a58d7d6d16e4ed6bb8dc54aeb6827014d402e09f44564bdb384d778",
    "0.2.0": "f3dab047a993b18ee5a660f72fec59d66beb71d32debf76b510d7d7a7369c980",
    "0.2.1": "ecce6147925428b0d821a2f66f6c776b4bbc476571366bd3a1de19f8703e9301",
}
paths = {pathlib.Path(arg).name: pathlib.Path(arg) for arg in sys.argv[1:]}
records = []
for version, digest in PACKAGES.items():
    package = paths[f"Axial-{version}-universal.pkg"]
    assert hashlib.sha256(package.read_bytes()).hexdigest() == digest, package
    with tempfile.TemporaryDirectory() as temporary:
        expanded = pathlib.Path(temporary) / "package"
        subprocess.run(["/usr/sbin/pkgutil", "--expand-full", str(package), str(expanded)], check=True)
        apps = list(expanded.glob("**/Payload/Applications/Axial.app"))
        assert len(apps) == 1
        payload = apps[0].parent.parent
        for name in ("Axial", "3DconnexionClient", "3DconnexionNavlib"):
            bundle = payload / ("Applications/Axial.app" if name == "Axial" else f"Library/Frameworks/{name}.framework")
            excluded = "Contents/Info.plist" if name == "Axial" else "Versions/A/Resources/Info.plist"
            for entry in [bundle, *sorted(bundle.rglob("*"))]:
                relative = entry.relative_to(bundle).as_posix()
                if relative == excluded:
                    continue
                if entry.is_symlink():
                    kind, value = "l", str(entry.readlink())
                elif entry.is_dir():
                    kind, value = "d", "-"
                else:
                    assert entry.is_file(), entry
                    kind, value = "f", hashlib.sha256(entry.read_bytes()).hexdigest()
                relative = "." if relative == "." else "./" + relative
                assert not any(c in relative + value for c in "|\n\r")
                records.append(f"{version}|{name}|{kind}|{value}|{relative}")

print("#!/bin/bash\n# Generated by tools/generate-legacy-files.py; do not edit records by hand.")
for version, digest in PACKAGES.items():
    print(f"# https://github.com/consi/axial/releases/download/v{version}/Axial-{version}-universal.pkg\n# SHA256 {digest}")
print("axial_known_files() {\n  cat <<'AXIAL_RELEASE_FILES'")
print("\n".join(records))
print("AXIAL_RELEASE_FILES\n}")
