#!/bin/bash
# Generated by tools/generate-legacy-files.py; do not edit records by hand.
# https://github.com/consi/axial/releases/download/v0.1.0/Axial-0.1.0-universal.pkg
# SHA256 a4ae851d8a58d7d6d16e4ed6bb8dc54aeb6827014d402e09f44564bdb384d778
# https://github.com/consi/axial/releases/download/v0.2.0/Axial-0.2.0-universal.pkg
# SHA256 f3dab047a993b18ee5a660f72fec59d66beb71d32debf76b510d7d7a7369c980
# https://github.com/consi/axial/releases/download/v0.2.1/Axial-0.2.1-universal.pkg
# SHA256 ecce6147925428b0d821a2f66f6c776b4bbc476571366bd3a1de19f8703e9301
axial_known_files() {
  cat <<'AXIAL_RELEASE_FILES'
0.1.0|Axial|d|-|.
0.1.0|Axial|d|-|./Contents
0.1.0|Axial|d|-|./Contents/Library
0.1.0|Axial|d|-|./Contents/Library/Helpers
0.1.0|Axial|d|-|./Contents/Library/Helpers/Axial Service.app
0.1.0|Axial|d|-|./Contents/Library/Helpers/Axial Service.app/Contents
0.1.0|Axial|f|533e8798c8b116e2828931aedc730d73e8327a9f2d332619978ba0f8ab17d497|./Contents/Library/Helpers/Axial Service.app/Contents/Info.plist
0.1.0|Axial|d|-|./Contents/Library/Helpers/Axial Service.app/Contents/MacOS
0.1.0|Axial|f|54f3dbc7d9bc8d3282bb8cdc5de512962eb3d7e2bdc808d852f86d8750362fbc|./Contents/Library/Helpers/Axial Service.app/Contents/MacOS/axial-service
0.1.0|Axial|d|-|./Contents/Library/Helpers/Axial Service.app/Contents/Resources
0.1.0|Axial|f|84a1e966d2a27c6a6506a2ace82e08818dd8672a91faebcf910216123cd54b41|./Contents/Library/Helpers/Axial Service.app/Contents/Resources/Axial.icns
0.1.0|Axial|d|-|./Contents/Library/Helpers/Axial Service.app/Contents/_CodeSignature
0.1.0|Axial|f|442c8b5015ed9b30ce7c50ad73aecfc34134e9eb0d118f3b792cd9c914b3310c|./Contents/Library/Helpers/Axial Service.app/Contents/_CodeSignature/CodeResources
0.1.0|Axial|f|62c91885980de1cb71bfa6ebcd71fcd7bee8b556d788f553b926ecac9a06bc98|./Contents/Library/Helpers/axialctl
0.1.0|Axial|d|-|./Contents/Library/LaunchAgents
0.1.0|Axial|f|6d1f3d97ebea17a049993606540faac523d6b3b06f7810f6e38503c36316498d|./Contents/Library/LaunchAgents/pro.jest.service.plist
0.1.0|Axial|d|-|./Contents/MacOS
0.1.0|Axial|f|8a38e57ae1170f06fcdb1de320fc7be38b9d72b2c8eb1f30cc28969f69255127|./Contents/MacOS/Axial
0.1.0|Axial|f|82502191c9484b04d685374f9879a0066069c49b8acae7a04b01d38d07e8eca0|./Contents/PkgInfo
0.1.0|Axial|d|-|./Contents/Resources
0.1.0|Axial|f|84a1e966d2a27c6a6506a2ace82e08818dd8672a91faebcf910216123cd54b41|./Contents/Resources/Axial.icns
0.1.0|Axial|f|5128a134fdd566a76468590d83bfc787d509fecd86d7c5d2f02840301642c5b7|./Contents/Resources/LICENSE
0.1.0|Axial|f|a2010f343487d3f7618affe54f789f5487602331c0a8d03f49e9a7c547cf0499|./Contents/Resources/ToyCar-CC0-1.0.txt
0.1.0|Axial|f|aed216cda25deab59a115bdd6f486da0437fe4e1d9df11c34e496242dbf89fe2|./Contents/Resources/ToyCar-credits.txt
0.1.0|Axial|f|5385dec528f82ce0f1d1bbe5145deff79acc3579b331f5a0acea520d151b6dd4|./Contents/Resources/ToyCar.scn
0.1.0|Axial|d|-|./Contents/_CodeSignature
0.1.0|Axial|f|7185bc96c6f2ce3d5555fc365ef40a49918131bd553249645b3081707e50bc62|./Contents/_CodeSignature/CodeResources
0.1.0|3DconnexionClient|d|-|.
0.1.0|3DconnexionClient|l|Versions/Current/3DconnexionClient|./3DconnexionClient
0.1.0|3DconnexionClient|l|Versions/Current/Headers|./Headers
0.1.0|3DconnexionClient|l|Versions/Current/Resources|./Resources
0.1.0|3DconnexionClient|d|-|./Versions
0.1.0|3DconnexionClient|d|-|./Versions/A
0.1.0|3DconnexionClient|f|ef8cacced183f4a45e7b4db8a174eec70e87ed85c63596bb9cac9a03c04a2bb0|./Versions/A/3DconnexionClient
0.1.0|3DconnexionClient|d|-|./Versions/A/Headers
0.1.0|3DconnexionClient|f|39997885b491eb1b8d019b9fe236288f2e38196854ba17dc4e6c553adf666559|./Versions/A/Headers/ConnexionClientAPI.h
0.1.0|3DconnexionClient|d|-|./Versions/A/Resources
0.1.0|3DconnexionClient|d|-|./Versions/A/_CodeSignature
0.1.0|3DconnexionClient|f|acec0e6b90e8553dd87b299a213bcf9b55c217af2d803ed1bafb78318e1cb20d|./Versions/A/_CodeSignature/CodeResources
0.1.0|3DconnexionClient|l|A|./Versions/Current
0.1.0|3DconnexionNavlib|d|-|.
0.1.0|3DconnexionNavlib|l|Versions/Current/3DconnexionNavlib|./3DconnexionNavlib
0.1.0|3DconnexionNavlib|l|Versions/Current/Headers|./Headers
0.1.0|3DconnexionNavlib|l|Versions/Current/Resources|./Resources
0.1.0|3DconnexionNavlib|d|-|./Versions
0.1.0|3DconnexionNavlib|d|-|./Versions/A
0.1.0|3DconnexionNavlib|f|4169cbb302b34db2cf795bf1f9654d8289fbee464cf52d6e21d1d0f63ca1bf3a|./Versions/A/3DconnexionNavlib
0.1.0|3DconnexionNavlib|d|-|./Versions/A/Headers
0.1.0|3DconnexionNavlib|d|-|./Versions/A/Headers/navlib
0.1.0|3DconnexionNavlib|f|4b332a937c948897911ef96467bd5a3432d93a06a6a99e8f3701da96cf517b33|./Versions/A/Headers/navlib/navlib.h
0.1.0|3DconnexionNavlib|f|c73a71303e665fd56180410cf726eaec41a9027d7ddef30300d6929eeafadc38|./Versions/A/Headers/navlib/navlib_defines.h
0.1.0|3DconnexionNavlib|f|09359b75c7b4c170ac1da75d3194b3e52ed330bcedb806765b56e9240a7a2d59|./Versions/A/Headers/navlib/navlib_templates.h
0.1.0|3DconnexionNavlib|f|7560c2ed133be82a6e1e611218a5646fdb67bbcd3a5564af13f3fdaea8fb4d6f|./Versions/A/Headers/navlib/navlib_types.h
0.1.0|3DconnexionNavlib|f|b870c7fd17141ea176364c81f5030d104ecb96f1467bf40654520e1f62e6cf5f|./Versions/A/Headers/siappcmd_types.h
0.1.0|3DconnexionNavlib|d|-|./Versions/A/Resources
0.1.0|3DconnexionNavlib|f|20e50fe7aae3e56378ebf0417d9de904f55a0e61e4df315333e632a4d3555d95|./Versions/A/Resources/LGPL-2.1.txt
0.1.0|3DconnexionNavlib|f|8e51eb11f2d043bdef73cdfe266c132a953e462d8c012dd34afda9f98ab8ab56|./Versions/A/Resources/UPSTREAM
0.1.0|3DconnexionNavlib|d|-|./Versions/A/_CodeSignature
0.1.0|3DconnexionNavlib|f|facd23385b659bf406684e50bc07b51d0bd4d0a28637423cdc01e6b979829090|./Versions/A/_CodeSignature/CodeResources
0.1.0|3DconnexionNavlib|l|A|./Versions/Current
0.2.0|Axial|d|-|.
0.2.0|Axial|d|-|./Contents
0.2.0|Axial|d|-|./Contents/Library
0.2.0|Axial|d|-|./Contents/Library/Helpers
0.2.0|Axial|d|-|./Contents/Library/Helpers/Axial Service.app
0.2.0|Axial|d|-|./Contents/Library/Helpers/Axial Service.app/Contents
0.2.0|Axial|f|5dd3357c5425ae0914167e44d362eeb78def46962dff7c1e10539db0554534fb|./Contents/Library/Helpers/Axial Service.app/Contents/Info.plist
0.2.0|Axial|d|-|./Contents/Library/Helpers/Axial Service.app/Contents/MacOS
0.2.0|Axial|f|0c6f34822da709bdfcb979dab69dfa3c3071f88a9884e674f1cc58b78cb288b7|./Contents/Library/Helpers/Axial Service.app/Contents/MacOS/axial-service
0.2.0|Axial|d|-|./Contents/Library/Helpers/Axial Service.app/Contents/Resources
0.2.0|Axial|f|84a1e966d2a27c6a6506a2ace82e08818dd8672a91faebcf910216123cd54b41|./Contents/Library/Helpers/Axial Service.app/Contents/Resources/Axial.icns
0.2.0|Axial|d|-|./Contents/Library/Helpers/Axial Service.app/Contents/_CodeSignature
0.2.0|Axial|f|442c8b5015ed9b30ce7c50ad73aecfc34134e9eb0d118f3b792cd9c914b3310c|./Contents/Library/Helpers/Axial Service.app/Contents/_CodeSignature/CodeResources
0.2.0|Axial|f|68bcc79053398b80e2e72329830db0756d084f99bb101c02388d1ac835352216|./Contents/Library/Helpers/axial-web-setup
0.2.0|Axial|f|3a223e24e6e3c39a5ae9bd870de75d21286b2ffc456e8970ecb90afb6d6d6cd8|./Contents/Library/Helpers/axialctl
0.2.0|Axial|d|-|./Contents/Library/LaunchAgents
0.2.0|Axial|f|6d1f3d97ebea17a049993606540faac523d6b3b06f7810f6e38503c36316498d|./Contents/Library/LaunchAgents/pro.jest.service.plist
0.2.0|Axial|d|-|./Contents/MacOS
0.2.0|Axial|f|56f0a62c9f10abe66034c6646adc532ed883a1bf4c1570e8bd900df9ca962f33|./Contents/MacOS/Axial
0.2.0|Axial|f|82502191c9484b04d685374f9879a0066069c49b8acae7a04b01d38d07e8eca0|./Contents/PkgInfo
0.2.0|Axial|d|-|./Contents/Resources
0.2.0|Axial|f|84a1e966d2a27c6a6506a2ace82e08818dd8672a91faebcf910216123cd54b41|./Contents/Resources/Axial.icns
0.2.0|Axial|f|5128a134fdd566a76468590d83bfc787d509fecd86d7c5d2f02840301642c5b7|./Contents/Resources/LICENSE
0.2.0|Axial|f|c9bff75738922193e67fa726fa225535870d2aa1059f91452c411736284ad566|./Contents/Resources/LICENSE_1_0.txt
0.2.0|Axial|f|7d5450cb2d142651b8afa315b5f238efc805dad827d91ba367d8516bc9d49e7a|./Contents/Resources/OpenSSL-LICENSE.txt
0.2.0|Axial|f|a2010f343487d3f7618affe54f789f5487602331c0a8d03f49e9a7c547cf0499|./Contents/Resources/ToyCar-CC0-1.0.txt
0.2.0|Axial|f|aed216cda25deab59a115bdd6f486da0437fe4e1d9df11c34e496242dbf89fe2|./Contents/Resources/ToyCar-credits.txt
0.2.0|Axial|f|5385dec528f82ce0f1d1bbe5145deff79acc3579b331f5a0acea520d151b6dd4|./Contents/Resources/ToyCar.scn
0.2.0|Axial|d|-|./Contents/_CodeSignature
0.2.0|Axial|f|5f5431455c0ab8ad60bfd4eefe04dc64dadc6a0c17c17611e072e0ab4d118b09|./Contents/_CodeSignature/CodeResources
0.2.0|3DconnexionClient|d|-|.
0.2.0|3DconnexionClient|l|Versions/Current/3DconnexionClient|./3DconnexionClient
0.2.0|3DconnexionClient|l|Versions/Current/Headers|./Headers
0.2.0|3DconnexionClient|l|Versions/Current/Resources|./Resources
0.2.0|3DconnexionClient|d|-|./Versions
0.2.0|3DconnexionClient|d|-|./Versions/A
0.2.0|3DconnexionClient|f|4390078ecafe096397dfe41b22a98698cc6e49bf745738a852a50be493e28b87|./Versions/A/3DconnexionClient
0.2.0|3DconnexionClient|d|-|./Versions/A/Headers
0.2.0|3DconnexionClient|f|2be7a77b031f40b1558e793592d4f7ad83b257e8a51f6bbd8016dc97ed1915c1|./Versions/A/Headers/ConnexionClientAPI.h
0.2.0|3DconnexionClient|d|-|./Versions/A/Resources
0.2.0|3DconnexionClient|d|-|./Versions/A/_CodeSignature
0.2.0|3DconnexionClient|f|11f73bbba696bf2d27c1be63db6d7040dc3fe46b4d18b5d2a6696763499b2554|./Versions/A/_CodeSignature/CodeResources
0.2.0|3DconnexionClient|l|A|./Versions/Current
0.2.0|3DconnexionNavlib|d|-|.
0.2.0|3DconnexionNavlib|l|Versions/Current/3DconnexionNavlib|./3DconnexionNavlib
0.2.0|3DconnexionNavlib|l|Versions/Current/Headers|./Headers
0.2.0|3DconnexionNavlib|l|Versions/Current/Resources|./Resources
0.2.0|3DconnexionNavlib|d|-|./Versions
0.2.0|3DconnexionNavlib|d|-|./Versions/A
0.2.0|3DconnexionNavlib|f|ba470c18d68feab5afe85739e7691588999a8f8421a66516a979aec63346efe0|./Versions/A/3DconnexionNavlib
0.2.0|3DconnexionNavlib|d|-|./Versions/A/Headers
0.2.0|3DconnexionNavlib|d|-|./Versions/A/Headers/navlib
0.2.0|3DconnexionNavlib|f|4b332a937c948897911ef96467bd5a3432d93a06a6a99e8f3701da96cf517b33|./Versions/A/Headers/navlib/navlib.h
0.2.0|3DconnexionNavlib|f|c73a71303e665fd56180410cf726eaec41a9027d7ddef30300d6929eeafadc38|./Versions/A/Headers/navlib/navlib_defines.h
0.2.0|3DconnexionNavlib|f|09359b75c7b4c170ac1da75d3194b3e52ed330bcedb806765b56e9240a7a2d59|./Versions/A/Headers/navlib/navlib_templates.h
0.2.0|3DconnexionNavlib|f|7560c2ed133be82a6e1e611218a5646fdb67bbcd3a5564af13f3fdaea8fb4d6f|./Versions/A/Headers/navlib/navlib_types.h
0.2.0|3DconnexionNavlib|f|b870c7fd17141ea176364c81f5030d104ecb96f1467bf40654520e1f62e6cf5f|./Versions/A/Headers/siappcmd_types.h
0.2.0|3DconnexionNavlib|d|-|./Versions/A/Resources
0.2.0|3DconnexionNavlib|f|20e50fe7aae3e56378ebf0417d9de904f55a0e61e4df315333e632a4d3555d95|./Versions/A/Resources/LGPL-2.1.txt
0.2.0|3DconnexionNavlib|f|8e51eb11f2d043bdef73cdfe266c132a953e462d8c012dd34afda9f98ab8ab56|./Versions/A/Resources/UPSTREAM
0.2.0|3DconnexionNavlib|d|-|./Versions/A/_CodeSignature
0.2.0|3DconnexionNavlib|f|acfcdeb8b93fcf399d36178ff048a9d38b792075631d8c8dbf7e29933e18b8ba|./Versions/A/_CodeSignature/CodeResources
0.2.0|3DconnexionNavlib|l|A|./Versions/Current
0.2.1|Axial|d|-|.
0.2.1|Axial|d|-|./Contents
0.2.1|Axial|d|-|./Contents/Library
0.2.1|Axial|d|-|./Contents/Library/Helpers
0.2.1|Axial|d|-|./Contents/Library/Helpers/Axial Service.app
0.2.1|Axial|d|-|./Contents/Library/Helpers/Axial Service.app/Contents
0.2.1|Axial|f|08a5e4d913f0ab8397a5f84e6ad9daa34a573ff52e4fd0180d6793ff9ba1759b|./Contents/Library/Helpers/Axial Service.app/Contents/Info.plist
0.2.1|Axial|d|-|./Contents/Library/Helpers/Axial Service.app/Contents/MacOS
0.2.1|Axial|f|000e1d2b0a388f3c812d1c59b9c79d1f5fd9d59a529094810c1cbdc55a90da1e|./Contents/Library/Helpers/Axial Service.app/Contents/MacOS/axial-service
0.2.1|Axial|d|-|./Contents/Library/Helpers/Axial Service.app/Contents/Resources
0.2.1|Axial|f|84a1e966d2a27c6a6506a2ace82e08818dd8672a91faebcf910216123cd54b41|./Contents/Library/Helpers/Axial Service.app/Contents/Resources/Axial.icns
0.2.1|Axial|d|-|./Contents/Library/Helpers/Axial Service.app/Contents/_CodeSignature
0.2.1|Axial|f|442c8b5015ed9b30ce7c50ad73aecfc34134e9eb0d118f3b792cd9c914b3310c|./Contents/Library/Helpers/Axial Service.app/Contents/_CodeSignature/CodeResources
0.2.1|Axial|f|68bcc79053398b80e2e72329830db0756d084f99bb101c02388d1ac835352216|./Contents/Library/Helpers/axial-web-setup
0.2.1|Axial|f|3a223e24e6e3c39a5ae9bd870de75d21286b2ffc456e8970ecb90afb6d6d6cd8|./Contents/Library/Helpers/axialctl
0.2.1|Axial|d|-|./Contents/Library/LaunchAgents
0.2.1|Axial|f|6d1f3d97ebea17a049993606540faac523d6b3b06f7810f6e38503c36316498d|./Contents/Library/LaunchAgents/pro.jest.service.plist
0.2.1|Axial|d|-|./Contents/MacOS
0.2.1|Axial|f|ccb280c8d7c7537a90fd31774690219efd59b3f4bc2463c08b6b80492acd7acd|./Contents/MacOS/Axial
0.2.1|Axial|f|82502191c9484b04d685374f9879a0066069c49b8acae7a04b01d38d07e8eca0|./Contents/PkgInfo
0.2.1|Axial|d|-|./Contents/Resources
0.2.1|Axial|f|84a1e966d2a27c6a6506a2ace82e08818dd8672a91faebcf910216123cd54b41|./Contents/Resources/Axial.icns
0.2.1|Axial|f|5128a134fdd566a76468590d83bfc787d509fecd86d7c5d2f02840301642c5b7|./Contents/Resources/LICENSE
0.2.1|Axial|f|c9bff75738922193e67fa726fa225535870d2aa1059f91452c411736284ad566|./Contents/Resources/LICENSE_1_0.txt
0.2.1|Axial|f|7d5450cb2d142651b8afa315b5f238efc805dad827d91ba367d8516bc9d49e7a|./Contents/Resources/OpenSSL-LICENSE.txt
0.2.1|Axial|f|a2010f343487d3f7618affe54f789f5487602331c0a8d03f49e9a7c547cf0499|./Contents/Resources/ToyCar-CC0-1.0.txt
0.2.1|Axial|f|aed216cda25deab59a115bdd6f486da0437fe4e1d9df11c34e496242dbf89fe2|./Contents/Resources/ToyCar-credits.txt
0.2.1|Axial|f|5385dec528f82ce0f1d1bbe5145deff79acc3579b331f5a0acea520d151b6dd4|./Contents/Resources/ToyCar.scn
0.2.1|Axial|d|-|./Contents/_CodeSignature
0.2.1|Axial|f|a847a030cfdc12cfee22fcf7de1021a0104c107be98dbe205420a62643058e58|./Contents/_CodeSignature/CodeResources
0.2.1|3DconnexionClient|d|-|.
0.2.1|3DconnexionClient|l|Versions/Current/3DconnexionClient|./3DconnexionClient
0.2.1|3DconnexionClient|l|Versions/Current/Headers|./Headers
0.2.1|3DconnexionClient|l|Versions/Current/Resources|./Resources
0.2.1|3DconnexionClient|d|-|./Versions
0.2.1|3DconnexionClient|d|-|./Versions/A
0.2.1|3DconnexionClient|f|4390078ecafe096397dfe41b22a98698cc6e49bf745738a852a50be493e28b87|./Versions/A/3DconnexionClient
0.2.1|3DconnexionClient|d|-|./Versions/A/Headers
0.2.1|3DconnexionClient|f|2be7a77b031f40b1558e793592d4f7ad83b257e8a51f6bbd8016dc97ed1915c1|./Versions/A/Headers/ConnexionClientAPI.h
0.2.1|3DconnexionClient|d|-|./Versions/A/Resources
0.2.1|3DconnexionClient|d|-|./Versions/A/_CodeSignature
0.2.1|3DconnexionClient|f|11f73bbba696bf2d27c1be63db6d7040dc3fe46b4d18b5d2a6696763499b2554|./Versions/A/_CodeSignature/CodeResources
0.2.1|3DconnexionClient|l|A|./Versions/Current
0.2.1|3DconnexionNavlib|d|-|.
0.2.1|3DconnexionNavlib|l|Versions/Current/3DconnexionNavlib|./3DconnexionNavlib
0.2.1|3DconnexionNavlib|l|Versions/Current/Headers|./Headers
0.2.1|3DconnexionNavlib|l|Versions/Current/Resources|./Resources
0.2.1|3DconnexionNavlib|d|-|./Versions
0.2.1|3DconnexionNavlib|d|-|./Versions/A
0.2.1|3DconnexionNavlib|f|ba470c18d68feab5afe85739e7691588999a8f8421a66516a979aec63346efe0|./Versions/A/3DconnexionNavlib
0.2.1|3DconnexionNavlib|d|-|./Versions/A/Headers
0.2.1|3DconnexionNavlib|d|-|./Versions/A/Headers/navlib
0.2.1|3DconnexionNavlib|f|4b332a937c948897911ef96467bd5a3432d93a06a6a99e8f3701da96cf517b33|./Versions/A/Headers/navlib/navlib.h
0.2.1|3DconnexionNavlib|f|c73a71303e665fd56180410cf726eaec41a9027d7ddef30300d6929eeafadc38|./Versions/A/Headers/navlib/navlib_defines.h
0.2.1|3DconnexionNavlib|f|09359b75c7b4c170ac1da75d3194b3e52ed330bcedb806765b56e9240a7a2d59|./Versions/A/Headers/navlib/navlib_templates.h
0.2.1|3DconnexionNavlib|f|7560c2ed133be82a6e1e611218a5646fdb67bbcd3a5564af13f3fdaea8fb4d6f|./Versions/A/Headers/navlib/navlib_types.h
0.2.1|3DconnexionNavlib|f|b870c7fd17141ea176364c81f5030d104ecb96f1467bf40654520e1f62e6cf5f|./Versions/A/Headers/siappcmd_types.h
0.2.1|3DconnexionNavlib|d|-|./Versions/A/Resources
0.2.1|3DconnexionNavlib|f|20e50fe7aae3e56378ebf0417d9de904f55a0e61e4df315333e632a4d3555d95|./Versions/A/Resources/LGPL-2.1.txt
0.2.1|3DconnexionNavlib|f|8e51eb11f2d043bdef73cdfe266c132a953e462d8c012dd34afda9f98ab8ab56|./Versions/A/Resources/UPSTREAM
0.2.1|3DconnexionNavlib|d|-|./Versions/A/_CodeSignature
0.2.1|3DconnexionNavlib|f|acfcdeb8b93fcf399d36178ff048a9d38b792075631d8c8dbf7e29933e18b8ba|./Versions/A/_CodeSignature/CodeResources
0.2.1|3DconnexionNavlib|l|A|./Versions/Current
AXIAL_RELEASE_FILES
}
