cmake_minimum_required(VERSION 3.29)
set(helper "${APP}/Contents/Library/Helpers/Axial Service.app")
file(MAKE_DIRECTORY "${helper}/Contents/MacOS" "${helper}/Contents/Resources" "${APP}/Contents/Library/LaunchAgents")
file(COPY_FILE "${SERVICE}" "${helper}/Contents/MacOS/axial-service" ONLY_IF_DIFFERENT)
file(COPY_FILE "${CLI}" "${APP}/Contents/Library/Helpers/axialctl" ONLY_IF_DIFFERENT)
file(COPY_FILE "${GENERATED}/AxialService.plist" "${helper}/Contents/Info.plist" ONLY_IF_DIFFERENT)
file(COPY_FILE "${GENERATED}/Axial.icns" "${helper}/Contents/Resources/Axial.icns" ONLY_IF_DIFFERENT)
file(COPY "${SOURCE_DIR}/app/Manifests/pro.jest.service.plist" DESTINATION "${APP}/Contents/Library/LaunchAgents")
file(COPY "${SOURCE_DIR}/LICENSE" DESTINATION "${APP}/Contents/Resources")
file(COPY_FILE "${SOURCE_DIR}/third_party/toycar/CC0-1.0.txt" "${APP}/Contents/Resources/ToyCar-CC0-1.0.txt" ONLY_IF_DIFFERENT)
file(COPY_FILE "${SOURCE_DIR}/third_party/toycar/UPSTREAM-README.md" "${APP}/Contents/Resources/ToyCar-credits.txt" ONLY_IF_DIFFERENT)
foreach(path IN ITEMS "${helper}" "${APP}/Contents/Library/Helpers/axialctl" "${APP}")
  execute_process(COMMAND /usr/bin/codesign --force --options runtime --sign "${IDENTITY}" "${path}" COMMAND_ERROR_IS_FATAL ANY)
endforeach()
