cmake_minimum_required(VERSION 3.29)
set(headers "${FRAMEWORK}/Versions/A/Headers")
file(MAKE_DIRECTORY "${headers}")
if(ADAPTER STREQUAL "Client")
  file(COPY_FILE "${SOURCE_DIR}/include/axial/connexion.h" "${headers}/ConnexionClientAPI.h" ONLY_IF_DIFFERENT)
else()
  file(COPY "${SOURCE_DIR}/third_party/freecad/navlib" "${SOURCE_DIR}/third_party/freecad/siappcmd_types.h" DESTINATION "${headers}")
  file(COPY "${SOURCE_DIR}/third_party/freecad/LGPL-2.1.txt" "${SOURCE_DIR}/third_party/freecad/UPSTREAM" DESTINATION "${FRAMEWORK}/Versions/A/Resources")
endif()
file(CREATE_LINK Versions/Current/Headers "${FRAMEWORK}/Headers" SYMBOLIC)
execute_process(COMMAND /usr/bin/codesign --force --sign "${IDENTITY}" "${FRAMEWORK}" COMMAND_ERROR_IS_FATAL ANY)
