add_executable(axial-bench tests/benchmark.cpp)
target_link_libraries(axial-bench PRIVATE axial-options)
add_executable(navlib-bench tests/navlib_benchmark.mm)
target_link_libraries(navlib-bench PRIVATE axial-options "-framework Foundation")
if(NOT BUILD_TESTING)
  return()
endif()
foreach(test IN ITEMS core transport owner application)
  add_executable(${test}-tests "tests/${test}_tests.cpp")
  target_link_libraries(${test}-tests PRIVATE axial-options)
endforeach()
add_test(NAME core COMMAND core-tests "${CMAKE_SOURCE_DIR}/tests/fixtures/spaceexplorer-motion.txt" "${CMAKE_SOURCE_DIR}/tests/fixtures/upstream-device-buttons.toml")
add_test(NAME transport COMMAND transport-tests)
add_test(NAME owner COMMAND owner-tests $<TARGET_FILE:axial-service>)
add_test(NAME application COMMAND application-tests)
add_test(NAME release-version COMMAND /bin/bash "${CMAKE_SOURCE_DIR}/tests/release_version.sh" "${CMAKE_SOURCE_DIR}")
add_test(NAME install-guard COMMAND /bin/bash "${CMAKE_SOURCE_DIR}/tests/install_guard.sh" "${CMAKE_SOURCE_DIR}")
add_executable(hold-framework tests/hold_framework.cpp)
add_test(NAME install-mapped-framework COMMAND /bin/bash "${CMAKE_SOURCE_DIR}/tests/mapped_install_guard.sh"
  "${CMAKE_SOURCE_DIR}" $<TARGET_FILE:hold-framework> $<TARGET_BUNDLE_DIR:3DconnexionClient> $<TARGET_BUNDLE_DIR:3DconnexionNavlib>)
add_executable(web-tests tests/web_tests.cpp)
target_link_libraries(web-tests PRIVATE axial-web)
add_executable(web-bench tests/web_benchmark.cpp)
target_link_libraries(web-bench PRIVATE axial-web)
add_test(NAME web COMMAND /bin/bash "${CMAKE_SOURCE_DIR}/tests/web_tests.sh" $<TARGET_FILE:axial-web-setup> $<TARGET_FILE:web-tests>)
set_tests_properties(web PROPERTIES LABELS native TIMEOUT 60)
add_executable(integration-tests tests/integration.mm app/bridge.cpp)
target_link_libraries(integration-tests PRIVATE axial-options "-framework Foundation")
add_test(NAME integration COMMAND integration-tests $<TARGET_FILE:axial-service> $<TARGET_FILE:3DconnexionClient> $<TARGET_FILE:3DconnexionNavlib>)
set_tests_properties(core transport owner integration PROPERTIES LABELS native TIMEOUT 60)
if(AXIAL_BUILD_APP)
  function(axial_swift_test name)
    add_executable(${name}-tests ${ARGN})
    axial_swift_platform(${name}-tests)
    target_compile_options(${name}-tests PRIVATE -parse-as-library)
    add_test(NAME ${name} COMMAND ${name}-tests)
    set_tests_properties(${name} PROPERTIES TIMEOUT 60 LABELS swift)
  endfunction()
  axial_swift_test(navigation app/TestNavigation.swift tests/test_navigation.swift)
  axial_swift_test(diagnostics app/Diagnostics.swift tests/diagnostic_history_tests.swift)
  axial_swift_test(session-log app/SessionLog.swift tests/session_log_tests.swift)
  axial_swift_test(web-setup app/WebSetup.swift tests/web_setup_tests.swift)
  axial_swift_test(app-instance app/AppInstance.swift tests/app_instance_tests.swift)
  foreach(test IN ITEMS model startup)
    if(test STREQUAL "startup")
      set(test_source tests/app_startup.swift)
    else()
      set(test_source tests/model_tests.swift)
    endif()
    axial_swift_test(${test} ${axial_app_sources} ${test_source})
    target_link_libraries(${test}-tests PRIVATE axial-bridge)
  endforeach()
  set_tests_properties(startup PROPERTIES LABELS "swift;gui" RUN_SERIAL TRUE)
endif()

if(AXIAL_BUILD_APP AND BUILD_TESTING)
  add_library(preview-test-bridge STATIC tests/preview_support.cpp)
  target_link_libraries(preview-test-bridge PRIVATE axial-options PUBLIC c++)
  add_executable(scene-performance ${axial_app_sources} tests/scene_performance.swift)
  axial_swift_platform(scene-performance)
  target_compile_options(scene-performance PRIVATE -parse-as-library)
  target_link_libraries(scene-performance PRIVATE preview-test-bridge)
  axial_swift_test(scene ${axial_app_sources} tests/scene_tests.swift)
  target_link_libraries(scene-tests PRIVATE preview-test-bridge)
  if(AXIAL_SCENE_BASELINE)
    set(baseline_sources ${axial_app_sources})
    list(REMOVE_ITEM baseline_sources app/SceneTest.swift)
    add_executable(scene-performance-baseline ${baseline_sources} "${AXIAL_SCENE_BASELINE}" tests/scene_performance.swift)
    axial_swift_platform(scene-performance-baseline)
    target_compile_options(scene-performance-baseline PRIVATE -parse-as-library)
    target_link_libraries(scene-performance-baseline PRIVATE preview-test-bridge)
  endif()
endif()
