add_executable(axial-bench tests/benchmark.cpp)
target_link_libraries(axial-bench PRIVATE axial-options)
if(NOT BUILD_TESTING)
  return()
endif()
foreach(test IN ITEMS core transport owner)
  add_executable(${test}-tests "tests/${test}_tests.cpp")
  target_link_libraries(${test}-tests PRIVATE axial-options)
endforeach()
add_test(NAME core COMMAND core-tests "${CMAKE_SOURCE_DIR}/tests/fixtures/spaceexplorer-motion.txt" "${CMAKE_SOURCE_DIR}/tests/fixtures/upstream-device-buttons.toml")
add_test(NAME transport COMMAND transport-tests)
add_test(NAME owner COMMAND owner-tests $<TARGET_FILE:axial-service>)
add_executable(integration-tests tests/integration.mm app/bridge.cpp)
target_link_libraries(integration-tests PRIVATE axial-options "-framework Foundation")
add_test(NAME integration COMMAND integration-tests $<TARGET_FILE:axial-service> $<TARGET_FILE:3DconnexionClient> $<TARGET_FILE:3DconnexionNavlib>)
set_tests_properties(core transport owner integration PROPERTIES LABELS native TIMEOUT 60)
if(AXIAL_BUILD_APP)
  function(axial_swift_test name)
    add_executable(${name}-tests ${ARGN})
    axial_swift_platform(${name}-tests)
    target_compile_options(${name}-tests PRIVATE -parse-as-library)
    add_test(NAME ${name} COMMAND ${name}-tests)
    set_tests_properties(${name} PROPERTIES TIMEOUT 60 LABELS swift)
  endfunction()
  axial_swift_test(navigation app/TestNavigation.swift tests/test_navigation.swift)
  axial_swift_test(diagnostics app/Diagnostics.swift tests/diagnostic_history_tests.swift)
  axial_swift_test(session-log app/SessionLog.swift tests/session_log_tests.swift)
  foreach(test IN ITEMS model startup)
    if(test STREQUAL "startup")
      set(test_source tests/app_startup.swift)
    else()
      set(test_source tests/model_tests.swift)
    endif()
    axial_swift_test(${test} ${axial_app_sources} ${test_source})
    target_link_libraries(${test}-tests PRIVATE axial-bridge)
  endforeach()
  set_tests_properties(startup PROPERTIES LABELS "swift;gui" RUN_SERIAL TRUE)
endif()
