file(STRINGS "${SOURCE_DIR}/third_party/toycar/SHA256SUMS" entries)
foreach(entry IN LISTS entries)
  if(NOT entry MATCHES "^([0-9a-f]+)  (.+)$")
    message(FATAL_ERROR "Invalid asset checksum entry")
  endif()
  set(expected "${CMAKE_MATCH_1}")
  set(path "${SOURCE_DIR}/${CMAKE_MATCH_2}")
  file(SHA256 "${path}" actual)
  if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "Asset checksum mismatch: ${path}")
  endif()
endforeach()
