cmake_minimum_required(VERSION 3.29)
# Verify the actual package payload, not just the install staging directory.
# A successful productbuild invocation can otherwise produce an empty installer.
foreach(package IN LISTS CPACK_PACKAGE_FILES)
  string(RANDOM LENGTH 12 token)
  set(expanded "${CPACK_PACKAGE_DIRECTORY}/.verify-${token}")
  execute_process(COMMAND /usr/sbin/pkgutil --expand-full "${package}" "${expanded}" COMMAND_ERROR_IS_FATAL ANY)
  file(GLOB_RECURSE entries LIST_DIRECTORIES TRUE "${expanded}/*")
  set(apps)
  foreach(entry IN LISTS entries)
    if(entry MATCHES "/Applications/Axial[.]app$")
      list(APPEND apps "${entry}")
    endif()
  endforeach()
  list(LENGTH apps count)
  if(NOT count EQUAL 1)
    message(FATAL_ERROR "Package must contain exactly one Axial.app: ${package}")
  endif()
  list(GET apps 0 app)
  foreach(entry IN LISTS entries)
    if(entry MATCHES "/PackageInfo$")
      execute_process(COMMAND /usr/bin/xmllint --xpath "count(/pkg-info/relocate/bundle)" "${entry}"
        OUTPUT_VARIABLE relocations OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
      if(NOT relocations STREQUAL "0")
        message(FATAL_ERROR "Installer must not relocate bundles to existing development copies: ${entry}")
      endif()
    endif()
    if(entry MATCHES "/Scripts/postinstall$")
      message(FATAL_ERROR "Web setup belongs to the app, not an installer postinstall program")
    endif()
  endforeach()
  foreach(resource IN ITEMS Contents/MacOS/Axial Contents/Resources/Axial.icns Contents/Resources/ToyCar.scn
      "Contents/Library/Helpers/Axial Service.app/Contents/MacOS/axial-service" Contents/Library/Helpers/axialctl
      Contents/Library/Helpers/axial-web-setup Contents/Resources/OpenSSL-LICENSE.txt)
    if(NOT EXISTS "${app}/${resource}")
      message(FATAL_ERROR "Package is missing ${resource}")
    endif()
  endforeach()
  execute_process(COMMAND /usr/bin/codesign --verify --deep --strict "${app}" COMMAND_ERROR_IS_FATAL ANY)
  execute_process(COMMAND /usr/libexec/PlistBuddy -c "Print :CFBundleIdentifier" "${app}/Contents/Info.plist"
    OUTPUT_VARIABLE app_identity OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
  if(NOT app_identity STREQUAL "pro.jest.Axial")
    message(FATAL_ERROR "Incorrect packaged app identity: ${app_identity}")
  endif()
  string(REGEX REPLACE "/Applications/Axial[.]app$" "" payload "${app}")
  foreach(name IN ITEMS 3DconnexionClient 3DconnexionNavlib)
    set(framework "${payload}/Library/Frameworks/${name}.framework")
    if(NOT EXISTS "${framework}/Versions/A/${name}")
      message(FATAL_ERROR "Package is missing ${name}")
    endif()
    execute_process(COMMAND /usr/bin/codesign --verify --deep --strict "${framework}" COMMAND_ERROR_IS_FATAL ANY)
    foreach(key IN ITEMS CFBundleIdentifier CFBundleExecutable CFBundleVersion CFBundleShortVersionString)
      execute_process(COMMAND /usr/libexec/PlistBuddy -c "Print :${key}" "${framework}/Resources/Info.plist"
        OUTPUT_VARIABLE value OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
      if(key STREQUAL "CFBundleIdentifier")
        set(expected "pro.jest.${name}")
      elseif(key STREQUAL "CFBundleExecutable")
        set(expected "${name}")
      else()
        set(expected "1.0.0")
      endif()
      if(NOT value STREQUAL expected)
        message(FATAL_ERROR "Incorrect packaged ${name} ${key}: ${value}")
      endif()
    endforeach()
    foreach(link IN ITEMS Resources Versions/Current ${name})
      if(NOT IS_SYMLINK "${framework}/${link}" OR NOT EXISTS "${framework}/${link}")
        message(FATAL_ERROR "Missing or broken framework link: ${framework}/${link}")
      endif()
    endforeach()
  endforeach()
  file(REMOVE_RECURSE "${expanded}")
endforeach()
