cmake_minimum_required(VERSION 3.29)
# Verify the actual package payload, not just the install staging directory.
# A successful productbuild invocation can otherwise produce an empty installer.
foreach(package IN LISTS CPACK_PACKAGE_FILES)
  string(RANDOM LENGTH 12 token)
  set(expanded "${CPACK_PACKAGE_DIRECTORY}/.verify-${token}")
  execute_process(COMMAND /usr/sbin/pkgutil --expand-full "${package}" "${expanded}" COMMAND_ERROR_IS_FATAL ANY)
  file(GLOB_RECURSE entries LIST_DIRECTORIES TRUE "${expanded}/*")
  set(apps)
  foreach(entry IN LISTS entries)
    if(entry MATCHES "/Applications/Axial[.]app$")
      list(APPEND apps "${entry}")
    endif()
  endforeach()
  list(LENGTH apps count)
  if(NOT count EQUAL 1)
    message(FATAL_ERROR "Package must contain exactly one Axial.app: ${package}")
  endif()
  list(GET apps 0 app)
  foreach(resource IN ITEMS Contents/MacOS/Axial Contents/Resources/Axial.icns Contents/Resources/ToyCar.scn
      "Contents/Library/Helpers/Axial Service.app/Contents/MacOS/axial-service" Contents/Library/Helpers/axialctl)
    if(NOT EXISTS "${app}/${resource}")
      message(FATAL_ERROR "Package is missing ${resource}")
    endif()
  endforeach()
  execute_process(COMMAND /usr/bin/codesign --verify --deep --strict "${app}" COMMAND_ERROR_IS_FATAL ANY)
  string(REGEX REPLACE "/Applications/Axial[.]app$" "" payload "${app}")
  foreach(name IN ITEMS 3DconnexionClient 3DconnexionNavlib)
    set(framework "${payload}/Library/Frameworks/${name}.framework")
    if(NOT EXISTS "${framework}/Versions/A/${name}")
      message(FATAL_ERROR "Package is missing ${name}")
    endif()
    execute_process(COMMAND /usr/bin/codesign --verify --deep --strict "${framework}" COMMAND_ERROR_IS_FATAL ANY)
  endforeach()
  file(REMOVE_RECURSE "${expanded}")
endforeach()
